#!/bin/bash
clear
echo -e "        \e[1;4;31mDestiCOM.net ARK-Server-Control\e[0m"
for i in {16..21} {21..16} ; do echo -en "\e[38;5;${i}m####\e[0m" ; done ; echo
echo ""
echo -e "    \e[1mMögliche Optionen:\e[0m"
for i in {16..21} {21..16} ; do echo -en "\e[38;5;${i}m----\e[0m" ; done ; echo
echo "    broadcast, motd, saveworld, kick, ban, unban"
echo "    restart, status, update, backup, start, stop"
for i in {16..21} {21..16} ; do echo -en "\e[38;5;${i}m----\e[0m" ; done ; echo
echo ""
echo "    'exit' beendet das Script!"
echo "    'help' gibt dir eine kleine Hilfe!"
echo ""
echo ""
echo ""
echo ""
read -p "    Was möchtest du tun? " ANTWORT

case "$ANTWORT" in

	broadcast|b)
		cd ~
		./asc/broadcast
			;;
	motd)
		cd ~
		./asc/motd
			;;
	saveworld|save)
		cd ~
		./asc/saveworld
			;;
	kick)
		cd ~
		./asc/kick
			;;
	ban)
		cd ~
		./asc/ban
			;;
	unban)
		cd ~
		./asc/unban
			;;
	restart)
		cd ~
		./asc/restart
			;;
	view|status)
		cd ~
		./asc/status
			;;
	update)
		cd ~
		./asc/update
			;;
	backup)
		cd ~
		./asc/backup
			;;
	start)
		cd ~
		./arkserver.sh start
			;;
	stop)
		cd ~
		./asc/stop
			;;
	help|h)
		cd ~
		./asc/help
			;;
	exit|e)
		exit 1
			;;
esac
		cd ~
		./start
exit 1
;;
