#!/bin/bash
clear
echo -e  "\e[1;4;31mDestiCOM.net ARK-Server-Control (by DerBorny)\e[0m"
echo "#############################################"
echo ""
echo "Mögliche Optionen:"
echo "broadcast, restart, status, update, backup, start, stop, help"
echo ""
echo ""
echo ""
read -p "Was möchtest du tun? " ANTWORT

case "$ANTWORT" in

	broadcast|b)
		cd ~
		./asc/broadcast
			;;
	restart)
		cd ~
		./asc/restart
			;;
	view|status)
		cd ~
		./asc/status
			;;
	update)
		cd ~
		./asc/update
			;;
	backup)
		cd ~
		./asc/backup
			;;
	start)
		cd ~
		./arkserver.sh start
			;;
	stop)
		cd ~
		./arkserver.sh stop
			;;
	help|h)
		cd ~
		./asc/help
			;;
esac
		cd ~
		./start
exit 1
;;
