#!/bin/bash
clear
echo -e  "\e[1;4;31mDestiCOM.net ARK-Server-Control (by DerBorny)\e[0m"
echo "#############################################"
echo ""
echo "Mögliche Optionen:"
echo "broadcast, motd, saveworld, kick, ban, unban, restart, status, update, backup, start, stop, help"
echo ""
echo "mit 'exit' wird das Script beendet!"
echo ""
echo ""
read -p "Was möchtest du tun? " ANTWORT

case "$ANTWORT" in

	broadcast|b)
		cd ~
		./asc/broadcast
			;;
	motd)
		cd ~
		./asc/motd
			;;
	saveworld|save)
		cd ~
		./asc/saveworld
			;;
	kick)
		cd ~
		./asc/kick
			;;
	ban)
		cd ~
		./asc/ban
			;;
	unban)
		cd ~
		./asc/unban
			;;
	restart)
		cd ~
		./asc/restart
			;;
	view|status)
		cd ~
		./asc/status
			;;
	update)
		cd ~
		./asc/update
			;;
	backup)
		cd ~
		./asc/backup
			;;
	start)
		cd ~
		./arkserver.sh start
			;;
	stop)
		cd ~
		./arkserver.sh stop
			;;
	help|h)
		cd ~
		./asc/help
			;;
	exit|e)
		exit 1
			;;
esac
		cd ~
		./start
exit 1
;;
