#!/bin/bash
#RCON Backup Script (by DerBorny)

DATE=$(date +%Y-%m-%d_%H-%M-%S)
BACKUP_FILE="/hdd/sdc/backups/arksrv/${DATE}.tgz"

# /
# - configuration.ini
# - Game.ini
# - GameUserSettings.ini
files="/home/arksrv/configuration.ini"
files="${files} /home/arksrv/Game.ini"
files="${files} /home/arksrv/GameUserSettings.ini"
    # /game/ShooterGame/Saved/
    # - /SavedArks/*.arkprofile
    # - /SavedArks/*.arktribe
    # - /SavedArks/TheIsland.ark
    # - /SavedArks/TheIsland_AntiCorruptionBackup.bak
    # - /SavedArks/TheIsland_NewLaunchBackup.bak
files="${files} /home/arksrv/game/ShooterGame/Saved/SavedArks/*.arkprofile"
files="${files} /home/arksrv/game/ShooterGame/Saved/SavedArks/*.arktribe"
files="${files} /home/arksrv/game/ShooterGame/Saved/SavedArks/TheIsland.ark"
files="${files} /home/arksrv/game/ShooterGame/Saved/SavedArks/TheIsland_AntiCorruptionBackup.bak"
files="${files} /home/arksrv/game/ShooterGame/Saved/SavedArks/TheIsland_NewLaunchBackup.bak"
clear
echo "Backup wird angefertigt!"
sleep 0.5
tar -czf $BACKUP_FILE $files 
clear
echo "Backup wurde angefertigt und in /hdd/sdc/backups/arksrv/ abgelegt!"
