#!/bin/bash
#RCON Ban Script (2016, by DerBorny)


##RCON CONFIGURATION##
source ./inc/.config
source /home/arksrv/asc/inc/.config




##DONT EDIT ANYTHING##
clear
echo -e  "\e[1;4;31mBan Script\e[0m"
echo "2016 - DerBorny"
echo "-----------------------------"
echo "Ban geht an: ${IP}:${PORT}"
echo ""
echo ""
echo "Folgende Spieler können durch Eingabe der SteamID gebannt werden"
echo ""
echo " Nr --- Spieler --- SteamID "
echo "-----------------------------"
clear
./asc/inc/rcon -P${PW} -a${IP} -p${PORT} ListPlayers
echo "-----------------------------"
echo ""
echo ""
read -p "Wen willst du bannen? (SteamID) " BANPLAYER
echo "${BANPLAYER}" >> /var/www/html/arkbans.txt
./asc/inc/rcon -P${PW} -a${IP} -p${PORT} BanPlayer $BANPLAYER

exit

