#!/bin/bash
#RCON SetMOTD Script (2016, by DerBorny)


##RCON CONFIGURATION##
source ./inc/.config
source /home/arksrv/asc/inc/.config




##DONT EDIT ANYTHING##
clear
echo -e  "\e[1;4;31mARK SetMOTD Script\e[0m"
echo "2016 - DerBorny"
echo "-----------------------------"
echo "MOTD geht an: ${IP}:${PORT}"
echo ""
echo ""
echo -e "\e[4mBitte gib deine Nachricht ein:\e[0m "
echo ""
echo ""
echo ""
echo ""
echo -n "Eingabe: "; read MESSAGE
echo ""
clear
echo "Folgende Nachricht wird als Message of the Day festgelegt:  ${MESSAGE}"
echo ""
echo ""
echo "Antwort vom Server: "
./asc/inc/rcon -P${PW} -a${IP} -p${PORT} SetMessageOfTheDay $MESSAGE
sleep 3
exit
