#!/bin/bash
#RCON Broadcast Script (2016, by DerBorny)


##RCON CONFIGURATION##
source ./inc/config




##DONT EDIT ANYTHING##
clear
echo -e  "\e[1;4;31mARK Broadcast Script\e[0m"
echo "2016 - DerBorny"
echo "-----------------------------"
echo "Broadcasts gehen an: ${IP}:${PORT}"
echo ""
echo ""
echo -e "\e[4mBitte gib deine Nachricht ein:\e[0m "
echo ""
echo ""
echo ""
echo ""
echo -n "Eingabe: "; read MESSAGE
echo ""
echo -e "\e[4mBitte gib den Abstand (in Sekunden) ein:\e[0m "
echo "3600 Sekunden = 60 Minuten"
echo "2700 Sekunden = 45 Minuten"
echo "1800 Sekunden = 30 Minuten"
echo "300 Sekunden = 5 Minuten"
echo ""
echo -n "Eingabe: ";read ABSTAND


echo "Broadcast 1"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 2"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 3"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 4"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 5"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 6"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 7"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 8"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 9"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 10"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 11"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 12"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 13"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 14"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 15"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 16"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 17"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 18"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 19"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}
echo "Broadcast 20"
./inc/rcon -P${PW} -a${IP} -p${PORT} broadcast $MESSAGE
sleep ${ABSTAND}

exit
